# Delineation heatmap

In [1]:
import numpy as np
import SimpleITK as sitk
import os


import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

import sys
"../scripts" not in sys.path and sys.path.insert(0, '../scripts')
import read_scans_utils
import image_scaling

In [4]:
PATH_TO_NIFTI_DELINEATIONS = "../data/Regions ground truth/delineations_nifti"
PATH_TO_RESAMPLED_NIFTI_DELINEATIONS = "../data/Regions ground truth/resampled_delineations_nifti"

## First: resampling all delineations to be of the same resolution

To condense all delineations into a heatmap they first need to be converted to the same resolution

In [3]:
image_scaling.resample_delineations_to_same_resolution(
    PATH_TO_NIFTI_DELINEATIONS,
    f"../data/Regions ground truth/resampled_delineations_nifti"
)

In [10]:
patient007 = sitk.ReadImage(f"{PATH_TO_NIFTI_DELINEATIONS}/MARPROC007_combined_delineation.nii.gz")
patient007_array = sitk.GetArrayFromImage(patient007)
print(patient007_array.shape)
print(np.unique(patient007_array, return_counts = True))
print("---\n")

patient009 = sitk.ReadImage(f"{PATH_TO_NIFTI_DELINEATIONS}/MARPROC009_combined_delineation.nii.gz")
patient009_array = sitk.GetArrayFromImage(patient009)
print(patient009_array.shape)
print(np.unique(patient009_array, return_counts = True))
print("---\n")


print("\nResampled: ")
patient009_resampled = sitk.ReadImage(f"{PATH_TO_RESAMPLED_NIFTI_DELINEATIONS}/MARPROC009.nii.gz")
patient009_resampled_array = sitk.GetArrayFromImage(patient009_resampled)
print(patient009_resampled_array.shape)
print(np.unique(patient009_resampled_array, return_counts = True))
print("---\n")


(30, 512, 512)
(array([0., 1., 2.]), array([7853629,    9624,    1067]))
---

(40, 720, 720)
(array([0., 1., 2., 3.]), array([20735303,      481,       97,      119]))
---


Resampled: 
(30, 512, 512)
(array([0], dtype=uint8), array([7864320]))
---



In [ ]:
import nilearn.image as ni_im

In [ ]:
original_t2 = first_patient.axialt2
first_patient_delineation = first_patient.model_data["region_delineation"]
print(first_patient_delineation.shape)

print("########\n")

second_patient_delineation = second_patient.model_data["region_delineation"]
print(second_patient_delineation.shape)

In [ ]:
print(np.unique(second_patient_delineation.get_fdata()[:, :, 0]))

In [ ]:
np.set_printoptions(threshold=sys.maxsize)


In [ ]:
for i, row in enumerate(second_patient_delineation.get_fdata()[:, :, 0]):
    if 1 in row or 2 in row or 3 in row:
        print(i)
        print(row)
        print()

In [ ]:
resampled_image = ni_im.resample_to_img(second_patient_delineation, first_patient_delineation)
print(resampled_image.shape)

### Creating the density mappings

In [ ]:
density_mapping_gg3 = np.zeros_like(first_patient.model_data["region_delineation"].get_fdata())
density_mapping_gg4 = np.zeros_like(first_patient.model_data["region_delineation"].get_fdata())
density_mapping_crib = np.zeros_like(first_patient.model_data["region_delineation"].get_fdata())

### Plotting

In [ ]:
def transparent_cmap(cmap, N=255):
    "Copy colormap and set alpha values"

    mycmap = cmap
    mycmap._init()
    mycmap._lut[:,-1] = np.linspace(0, 0.8, N+4)
    return mycmap

In [ ]:
fig, ax = plt.subplots(1, 1)
ax.imshow(original_t2.get_fdata()[:, :, 15])
transparent_heatmap = transparent_cmap(plt.cm.Reds)

w, h = original_t2.get_fdata()[:, :, 15].shape
y, x = np.mgrid[0:h, 0:w]


# cb = ax.contourf(x, y, first_patient_delineation, 5, cmap = transparent_heatmap)
cb = ax.contourf(x, y, first_patient_delineation, 5, cmap = plt.cm.Reds)

plt.colorbar(cb)
plt.show()